import type { Metadata } from "next";
import { Montserrat, Inter } from "next/font/google";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { BookACallDialogProvider } from "@/components/landing/BookACallDialog";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${inter.variable} flex min-h-screen flex-col font-sans antialiased`}
      >
        <BookACallDialogProvider>
          <Header />
          <main className="flex-1">{children}</main>
          <Footer />
        </BookACallDialogProvider>
      </body>
    </html>
  );
}
